# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    # branches: [ "main", "feature_kheng" ]
    branches: [ "feature_kheng" ]
  pull_request:
    # branches: [ "main", "feature_kheng" ]
    branches: [ "feature_kheng" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Start microservices
      run: |
        npm inint -y
        npm install

        MS_PATH=src/api

        npm run apply_role_complexMS --prefix ${MS_PATH}
        npm run roledetails --prefix ${MS_PATH}
        npm run role_skills_ms --prefix ${MS_PATH}
        npm run skill_details_ms --prefix ${MS_PATH}

    - name: Run tests
      run: python -m unittest src/tests/test_complexMS.py
